---
deployment:
    tasks:
        - export PUBLICPATH=/home/u772220/public_html
        - export DEPLOYPATH=/home/u7722220/public_html/dashboard-mutu
        - /usr/bin/rsync -Paz . $DEPLOYPATH
        - cp -r $DEPLOYPATH $PUBLICPATH/stpbonaventura
