version: '3.2'
services:
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=mutu_dev
      - MYSQL_USER=dashboard-mutu
      - MYSQL_PASSWORD=secret
    networks:
      - app-network
    volumes:
      - 'app-volume:/var/lib/mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
networks:
  app-network:
    driver: bridge
volumes:
  app-volume: null
