<?php


namespace akreditasi\models\kriteria9\forms\resource;


use yii\base\Model;

class ResourceProdiForm extends Model
{

    public $id;
    public $nama;
    public $jenis;
    public $tujuan;
    public $sebagai;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function save(){


    }
}
